# docker-compose.yml
version: '2'
services:
    prometheus:
        image: zeiot/rpi-prometheus:1.1.2
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
        command:
            - '-config.file=/etc/prometheus/prometheus.yml'
        ports:
            - '9090:9090'
    grafana:
        image: zeiot/rpi-grafana:3.1.1
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=pass
        volumes:
            - grafana_data:/var/lib/grafana
        depends_on:
            - prometheus